import React, { useEffect } from 'react';
import { Element, scroller } from 'react-scroll';
import { useLocation } from 'react-router-dom';

const TevProjectPage: React.FC = () => {
  const location = useLocation();

  useEffect(() => {
    scroller.scrollTo('tev', {
      offset: -50,
    });
  }, [location.state]);
  return (
    <div
      style={{
        marginTop: '4rem',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      }}
    >
      <Element name="tev">
        <h1>Tarigma Event Viewer</h1>
      </Element>
      <iframe
        style={{ marginBottom: '2rem' }}
        width="560"
        height="315"
        src="https://www.youtube.com/embed/iVPHF3RrslQ?si=-XufhCxOcyv6pPG3"
        title="YouTube video player"
        frameBorder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        referrerPolicy="strict-origin-when-cross-origin"
        allowFullScreen
      ></iframe>

      <p
        style={{
          width: '50%',
          textAlign: 'center',
        }}
      >
        The Tarigma Event Viewer is a dashboard I created for viewing and
        analyzing data generated by electrical faults. Everything is rendered
        front-end using React and BlueprintJS for styling. The hardest part of
        the project was creating the custom cursors, which were used to select
        the time range of the data and had to be synchronized across multiple
        charts of different zoom levels and sizes.
      </p>
    </div>
  );
};

export default TevProjectPage;
